development:
 adapter: postgresql
 database: rspec_development
 host: localhost

test:
 adapter: postgresql
 database: rspec_test
 host: localhost

production:
 adapter: postgresql
 database: rspec_production
